name: Flutter CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  analyze:
    name: Analyze Flutter Code
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1

      # Run flutter analyze
      - name: Analyze Flutter Code
        run: flutter analyze

  test:
    name: Run Flutter Tests
    runs-on: ubuntu-latest
    needs: analyze

    steps:
      # Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Flutter
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.27.1

      # Cache dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      # Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Run tests
      - name: Run Flutter Tests
        run: flutter test
