name: Flutter Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Flutter and output version
      - name: Set up Flutter
        id: flutter-setup
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.5

      # Step 3: Cache Flutter SDK
      - name: Cache Flutter SDK
        uses: actions/cache@v3
        with:
          path: ~/.flutter-sdk
          key: ${{ runner.os }}-flutter-${{ steps.flutter-setup.outputs.flutter-version }}
          restore-keys: |
            ${{ runner.os }}-flutter-

      # Step 4: Cache Flutter dependencies
      - name: Cache Flutter dependencies
        uses: actions/cache@v3
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-cache-${{ hashFiles('**/pubspec.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pub-cache-

      # Step 5: Install dependencies
      - name: Install dependencies
        run: flutter pub get

      # Step 6: Analyze the code
      - name: Analyze Flutter code
        run: flutter analyze

      # Step 7: Run tests
      - name: Run Flutter tests
        run: flutter test
